texts:
- story_id: T1
  source_text_id: t1
  title_ja: 懐中時計
  title_en: The Pocket Watch
  title_zh: 懷中時計
  author_ja: 夢野久作
  author_en: Kyusaku Yumeno
  author_zh: 夢野久作
- story_id: T2
  source_text_id: t2
  title_ja: お金とピストル
  title_en: The Money and the Pistol
  title_zh: 錢與手槍
  author_ja: 夢野久作
  author_en: Kyusaku Yumeno
  author_zh: 夢野久作
- story_id: T3
  source_text_id: t3
  title_ja: ぼろぼろな駝鳥
  title_en: The Tattered Ostrich
  title_zh: 襤褸的鴕鳥
  author_ja: 高村光太郎
  author_en: Kotaro Takamura
  author_zh: 高村光太郎
